# Generated by Django 3.0.8 on 2020-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('carmodel', models.CharField(default='', max_length=1000)),
                ('carnum', models.CharField(default='', max_length=1000)),
                ('contactnum', models.CharField(default='', max_length=1000)),
                ('location', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
