# Generated by Django 3.0.8 on 2020-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20200709_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
