# Generated by Django 3.0.8 on 2020-07-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_auto_20200709_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=250)),
                ('pickup_time', models.DateTimeField()),
                ('p_pickup', models.CharField(default='', max_length=250)),
                ('p_destination', models.CharField(default='', max_length=250)),
                ('p_phone', models.CharField(default='', max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.Employee')),
            ],
        ),
    ]
